### ISSUE TITLE
请问 我配置了之后，push源码之后，为什么 traviceCI没有出发构建

### ISSUE THREAD

**Issue by williamHappy** [xiong-it/xiong-it.github.io#1]

**Comment by xiong-it** [comment]
原因可能是:push的分支是否正确？travice平台没有设置好；yml文件是否配置正确？其他还需要自己慢慢排查，我最开始也是碰到困难，摸索了几天。

**Comment by williamHappy** [comment]
嗯呢 解决了 配置文件的问题


来自 魅族 PRO 6

-------- 原始邮件 --------
发件人：MichaelX <notifications@github.com>
时间：2018年5月10日 16:26
收件人："xiong-it/xiong-it.github.io" <xiong-it.github.io@noreply.github.com>
抄送：willHappy <ctwang1994@163.com>,Author <author@noreply.github.com>
主题：Re: [xiong-it/xiong-it.github.io] 请问 我配置了之后，push源码之后，为什么 traviceCI没有出发构建 (#1)
